version: "3.8"

services:

  redis:
    image: redis:alpine
    container_name: redis
    restart: on-failure
    ports:
      - '6379:6379'    
    volumes: 
      - cache:/data
    networks:
      - default

  app:
    container_name: imagebot
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - redis
    networks:
      - default
    command: "python botmain.py"

networks:
  default:
    driver: overlay

volumes:
  cache: